---
ID: "b3cc5d09-9ade-4e42-b667-4cd0fe982697"
Parent: "33558292-0a36-498b-8bb8-c3f958990b8a"
Template: "33558292-0a36-498b-8bb8-c3f958990b8a"
Path: /sitecore/templates/Feature/Promotions/Item Listing Settings/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{35188EFC-D7BB-409A-83EF-D64BA9821B68}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180923T011647Z
