---
ID: "18e2e79c-86c7-44c6-995a-0ac538598ae6"
Parent: "ebb60f61-cc55-4107-8d70-53e347ba2b3d"
Template: "ebb60f61-cc55-4107-8d70-53e347ba2b3d"
Path: /sitecore/templates/Feature/Navigation/Link Menu Item/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{EBB60F61-CC55-4107-8D70-53E347BA2B3D}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "24050942-515c-4a6e-a121-19748b526988"
      Hint: Show Title
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180912T000343Z
    - ID: "841fe4fb-742f-4f0d-89f0-8a372a7a399d"
      Hint: Link
      Value: |
        <link text="$name" linktype="external" url="" anchor="" target="" />
